name = "ernisto/ocean"
version = "0.1.0"
description = "a package to simulate oceans"
authors = [
    "ernisto <joaovitordesouza707@gmail.com>"
]
repository = "https://github.com/ernisto/ocean"
license = "MIT"

[target]
environment = "roblox"
build_files = ["src"]
lib = "src/init.luau"
# bin = "src/cli.luau"

[engines]
pesde = "^0.6.0"
lune = "^0.8.9"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
luau_lsp = { name = "pesde/luau_lsp", version = "^1.39.0", target = "lune" }
asphalt = { name = "pesde/asphalt", version = "^0.9.1", target = "lune" }
stylua = { name = "pesde/stylua", version = "^2.0.2", target = "lune" }

# modules
uilabs = { name = "pepeeltoro41/ui_labs", version = "^2.3.7" }

[dependencies]
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
