name = "ernisto/ocean_demo"
version = "1.0.0"
description = "a demo of ocean simulation"
private = true

[target]
environment = "roblox"
build_files = ["client"]
lib = "lib/init.luau"
# bin = "cli/init.luau"

[engines]
pesde = "^0.6.0"
lune = "^0.8.9"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"
